package com.example.funny_cats.util


object RussianTranslator {

    // Перевод стран происхождения
    private val originTranslations = mapOf(
        "United States" to "США",
        "United Kingdom" to "Великобритания",
        "UK" to "Великобритания",
        "Russia" to "Россия",
        "Turkey" to "Турция",
        "Egypt" to "Египет",
        "Thailand" to "Таиланд",
        "Iran" to "Иран",
        "Japan" to "Япония",
        "China" to "Китай",
        "Italy" to "Италия",
        "Spain" to "Испания",
        "Canada" to "Канада",
        "Australia" to "Австралия",
        "Germany" to "Германия",
        "France" to "Франция",
        "Brazil" to "Бразилия",
        "Norway" to "Норвегия",
        "Sweden" to "Швеция",
        "Finland" to "Финляндия",
        "Denmark" to "Дания",
        "Iceland" to "Исландия",
        "Scotland" to "Шотландия",
        "Ireland" to "Ирландия",
        "Mexico" to "Мексика",
        "Argentina" to "Аргентина",
        "Chile" to "Чили",
        "Peru" to "Перу",
        "India" to "Индия",
        "Korea" to "Корея",
        "Vietnam" to "Вьетнам",
        "Philippines" to "Филиппины",
        "Indonesia" to "Индонезия",
        "Malaysia" to "Малайзия",
        "Singapore" to "Сингапур",
        "South Africa" to "Южная Африка",
        "Kenya" to "Кения",
        "Ethiopia" to "Эфиопия",
        "Morocco" to "Марокко",
        "Tunisia" to "Тунис",
        "Israel" to "Израиль",
        "Saudi Arabia" to "Саудовская Аравия",
        "United Arab Emirates" to "Объединенные Арабские Эмираты",
        "Burma" to "Мьянма",
        "Taiwan" to "Тайвань",
        "Cyprus" to "Кипр",
        "Sri Lanka" to "Шри-Ланка",
        "Greece" to "Греция",
        "Isle of Man" to "Остров Мэн",
        "Somalia" to "Сомали",
        "Ukraine" to "Украина",
        "Poland" to "Польша",
        "Hungary" to "Венгрия",
        "Czech Republic" to "Чехия",
        "Austria" to "Австрия",
        "Switzerland" to "Швейцария",
        "Netherlands" to "Нидерланды",
        "Belgium" to "Бельгия",
        "Portugal" to "Португалия",
        "Romania" to "Румыния",
        "Bulgaria" to "Болгария",
        "Serbia" to "Сербия",
        "Croatia" to "Хорватия",
        "Slovenia" to "Словения",
        "Slovakia" to "Словакия",
        "Lithuania" to "Литва",
        "Latvia" to "Латвия",
        "Estonia" to "Эстония",
        "Georgia" to "Грузия",
        "Armenia" to "Армения",
        "Azerbaijan" to "Азербайджан",
        "Kazakhstan" to "Казахстан",
        "Uzbekistan" to "Узбекистан",
        "Pakistan" to "Пакистан",
        "Bangladesh" to "Бангладеш",
        "Myanmar" to "Мьянма",
        "Laos" to "Лаос",
        "Cambodia" to "Камбоджа",
        "Mongolia" to "Монголия",
        "Nepal" to "Непал",
        "Bhutan" to "Бутан",
        "Afghanistan" to "Афганистан",
        "Iraq" to "Ирак",
        "Syria" to "Сирия",
        "Jordan" to "Иордания",
        "Lebanon" to "Ливан",
        "Yemen" to "Йемен",
        "Oman" to "Оман",
        "Qatar" to "Катар",
        "Kuwait" to "Кувейт",
        "Bahrain" to "Бахрейн"
    )

    // Перевод характеристик темперамента
    private val temperamentTranslations = mapOf(
        "Active" to "Активный",
        "Affectionate" to "Ласковый",
        "Agile" to "Проворный",
        "Alert" to "Бдительный",
        "Calm" to "Спокойный",
        "Curious" to "Любопытный",
        "Energetic" to "Энергичный",
        "Friendly" to "Дружелюбный",
        "Gentle" to "Нежный",
        "Independent" to "Независимый",
        "Intelligent" to "Умный",
        "Lively" to "Жизнерадостный",
        "Loyal" to "Преданный",
        "Playful" to "Игривый",
        "Quiet" to "Тихий",
        "Social" to "Общительный",
        "Sweet" to "Сладкий",
        "Territorial" to "Территориальный",
        "Vocal" to "Разговорчивый",
        "Wild" to "Дикий",
        "Adaptable" to "Адаптивный",
        "Adventurous" to "Авантюрный",
        "Brave" to "Храбрый",
        "Cautious" to "Осторожный",
        "Clownish" to "Клоунский",
        "Dog-like" to "Похожий на собаку",
        "Dominant" to "Доминантный",
        "Dignified" to "Благородный",
        "Easygoing" to "Неприхотливый",
        "Familial" to "Семейный",
        "Feisty" to "Воинственный",
        "Inquisitive" to "Пытливый",
        "Keen" to "Проницательный",
        "Obedient" to "Послушный",
        "Outgoing" to "Коммуникабельный",
        "Patient" to "Терпеливый",
        "People-oriented" to "Ориентированный на людей",
        "Relaxed" to "Расслабленный",
        "Responsible" to "Ответственный",
        "Sensitive" to "Чувствительный",
        "Shy" to "Стеснительный",
        "Smart" to "Смышлёный",
        "Stubborn" to "Упрямый",
        "Talkative" to "Болтливый",
        "Trainable" to "Обучаемый",
        "Trusting" to "Доверчивый",
        "Demanding" to "Требовательный",
        "Devoted" to "Преданный",
        "Easy Going" to "Неприхотливый",
        "Good-natured" to "Добродушный",
        "Graceful" to "Грациозный",
        "Happy" to "Счастливый",
        "Kind" to "Добрый",
        "Loving" to "Любящий",
        "Mischievous" to "Озорной",
        "Peaceful" to "Миролюбивый",
        "Perceptive" to "Восприимчивый",
        "Powerful" to "Мощный",
        "Quick" to "Быстрый",
        "Reserved" to "Сдержанный",
        "Robust" to "Крепкий",
        "Sophisticated" to "Искушенный",
        "Spirited" to "Энергичный",
        "Steady" to "Уравновешенный",
        "Strong" to "Сильный",
        "Tenacious" to "Упорный",
        "Thoughtful" to "Вдумчивый",
        "Vigilant" to "Бдительный",
        "Vivacious" to "Живой",
        "Witty" to "Остроумный",
        "Zesty" to "Энергичный"
    )

    // Перевод названий пород (ВСЕ породы из API)
    private val breedNameTranslations = mapOf(
        "Abyssinian" to "Абиссинская",
        "Aegean" to "Эгейская",
        "American Bobtail" to "Американский бобтейл",
        "American Curl" to "Американский кёрл",
        "American Shorthair" to "Американская короткошёрстная",
        "American Wirehair" to "Американская жесткошёрстная",
        "Arabian Mau" to "Аравийский мау",
        "Australian Mist" to "Австралийский мист",
        "Balinese" to "Балинезийская",
        "Bambino" to "Бамбино",
        "Bengal" to "Бенгальская",
        "Birman" to "Бирманская",
        "Bombay" to "Бомбейская",
        "British Longhair" to "Британская длинношёрстная",
        "British Shorthair" to "Британская короткошёрстная",
        "Burmese" to "Бурманская",
        "Burmilla" to "Бурмилла",
        "California Spangled" to "Калифорнийская сияющая",
        "Chantilly-Tiffany" to "Шантильи-тиффани",
        "Chartreux" to "Шартрез",
        "Chausie" to "Чаузи",
        "Cheetoh" to "Чито",
        "Colorpoint Shorthair" to "Колорпойнт короткошёрстная",
        "Cornish Rex" to "Корниш рекс",
        "Cymric" to "Кимрик",
        "Cyprus" to "Кипрская",
        "Devon Rex" to "Девон рекс",
        "Donskoy" to "Донской сфинкс",
        "Dragon Li" to "Дракон Ли",
        "Egyptian Mau" to "Египетская мау",
        "European Burmese" to "Европейская бурманская",
        "Exotic Shorthair" to "Экзотическая короткошёрстная",
        "Havana Brown" to "Гавана браун",
        "Himalayan" to "Гималайская",
        "Japanese Bobtail" to "Японский бобтейл",
        "Javanese" to "Яванская",
        "Khao Manee" to "Као-мани",
        "Korat" to "Корат",
        "Kurilian" to "Курильский бобтейл",
        "LaPerm" to "Лаперм",
        "Maine Coon" to "Мейн-кун",
        "Malayan" to "Малайская",
        "Manx" to "Мэнкс",
        "Munchkin" to "Манчкин",
        "Nebelung" to "Нибелунг",
        "Norwegian Forest Cat" to "Норвежская лесная",
        "Ocicat" to "Оцикет",
        "Oriental" to "Ориентальная",
        "Persian" to "Персидская",
        "Pixie-bob" to "Пикси-боб",
        "Ragamuffin" to "Рагамаффин",
        "Ragdoll" to "Рэгдолл",
        "Russian Blue" to "Русская голубая",
        "Savannah" to "Саванна",
        "Scottish Fold" to "Шотландская вислоухая",
        "Selkirk Rex" to "Селкирк рекс",
        "Siamese" to "Сиамская",
        "Siberian" to "Сибирская",
        "Singapura" to "Сингапурская",
        "Snowshoe" to "Сноу-шу",
        "Somali" to "Сомали",
        "Sphynx" to "Сфинкс",
        "Tonkinese" to "Тонкинская",
        "Toyger" to "Тойгер",
        "Turkish Angora" to "Турецкая ангора",
        "Turkish Van" to "Турецкий ван",
        "York Chocolate" to "Йоркская шоколадная"
    )

    fun translateBreedName(englishName: String): String {
        return breedNameTranslations[englishName] ?: englishName
    }

    fun translateOrigin(origin: String?): String {
        if (origin.isNullOrEmpty()) return "Неизвестно"
        return originTranslations[origin] ?: origin
    }

    fun translateTemperament(temperament: String?): String {
        if (temperament.isNullOrEmpty()) return "Не указан"

        var translated = temperament!!
        temperamentTranslations.forEach { (en, ru) ->
            translated = translated.replace(en, ru, ignoreCase = true)
        }
        return translated
    }


    // Функция для получения переведенного темперамента в виде списка (для отображения в списке)
    fun getShortTemperament(temperament: String?): String {
        if (temperament.isNullOrEmpty()) return "Характер не указан"

        val translated = translateTemperament(temperament)
        val qualities = translated.split(",").map { it.trim() }

        return if (qualities.size > 2) {
            qualities.take(2).joinToString(", ") + "..."
        } else {
            translated
        }
    }
}